datasets:
  taxi:
    column_mapping:
      categorical_features:
        - 'Airline'
        - 'Source'
        - 'Destination'
        - 'Total_Stops'
      numerical_features:
        - 'Price'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/flights_1.parquet
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
